[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'aperezdc/vim-template'

[[plugins]]
repo = 'sjl/gundo.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'vim-scripts/TwitVim'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'sakuraiyuta/commentout.vim'

[[plugins]]
repo = 'akiwoRM/vim2maya.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'fuenor/im_control.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

